name: Mark stale issues

on:
  workflow_dispatch: # for manual run
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

permissions:
  contents: write # only for delete-branch option
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Mark stale issues
        uses: actions/stale@v8
        with:
          repo-token: ${{ github.token }}
          days-before-stale: 15
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
          days-before-close: 7
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security'
